// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ArrowUp: typeof import('./src/components/icons/ArrowUp.vue')['default']
    ConnectWalletButton: typeof import('./src/components/ConnectWalletButton.vue')['default']
    IMdiBrightness4: typeof import('~icons/mdi/brightness4')['default']
    IMdiBrightness7: typeof import('~icons/mdi/brightness7')['default']
    IMdiFlashOutline: typeof import('~icons/mdi/flash-outline')['default']
    IMdiTimerSand: typeof import('~icons/mdi/timer-sand')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    IRiClipboardLine: typeof import('~icons/ri/clipboard-line')['default']
    IRiExternalLinkFill: typeof import('~icons/ri/external-link-fill')['default']
    IRiFileList3Line: typeof import('~icons/ri/file-list3-line')['default']
    NftCard: typeof import('./src/components/NftCard.vue')['default']
    PanelResult: typeof import('./src/components/VUpload/PanelResult.vue')['default']
    PanelUpload: typeof import('./src/components/VUpload/PanelUpload.vue')['default']
    PauseButton: typeof import('./src/components/icons/PauseButton.vue')['default']
    PlayButton: typeof import('./src/components/icons/PlayButton.vue')['default']
    PlayButtonBlue: typeof import('./src/components/icons/PlayButtonBlue.vue')['default']
    PlayButtonPink: typeof import('./src/components/icons/PlayButtonPink.vue')['default']
    PlayButtonPurple: typeof import('./src/components/icons/PlayButtonPurple.vue')['default']
    PlayButtonWhite: typeof import('./src/components/icons/PlayButtonWhite.vue')['default']
    Quotes: typeof import('./src/components/icons/Quotes.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/VUpload/SearchResult.vue')['default']
    StopButton: typeof import('./src/components/icons/StopButton.vue')['default']
    TokenCard: typeof import('./src/components/TokenCard.vue')['default']
    TokenView: typeof import('./src/components/TokenView.vue')['default']
    TrackPlayer: typeof import('./src/components/TrackPlayer.vue')['default']
  }
}

export {}
